version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run: echo $CIRCLE_BRANCH
      - run: if [ $CIRCLE_BRANCH == 'master' ]; then export REACT_APP_MY_NAME=ALEXANDRE; else export REACT_APP_MY_NAME=SEM_NOME; fi
      - run: echo $REACT_APP_MY_NAME
workflows:
    build-and-test:
      jobs:
        - build-and-test
