version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run: echo $CIRCLE_BRANCH
      - run: echo 'export REACT_APP_MY_NAME="test"' >> $BASH_ENV
      - run: source $BASH_ENV
      - run: echo $REACT_APP_MY_NAME
workflows:
    build-and-test:
      jobs:
        - build-and-test
